### ISSUE TITLE
Using reframe-utils more than one source

### ISSUE THREAD

**Issue by fdabrao** [nikolap/reframe-utils#2]
Hello all,

Can I use `multi-generation reg-basic-sub` in more than one .cljs source? It will clean the old first one?

Regards

**Comment by nikolap** [comment]
Assuming you're registering unique subscriptions, then it won't overwrite any previously registered ones. What I mean by this is the following code

```clojure
;; namespace 'a'
(multi-generation
    reg-basic-sub
    :active-page
    :cursor)
;; namespace 'b'
(multi-generation
    reg-basic-sub
    :special-timer
    :dumb-timer)
```

Will create the subscriptions :active-page, :cursor, :special-time, and :dumb-timer. Each of those point to the respective keys in the re-frame db.

However, doing something like this:

```clojure
;; namespace 'c'
(multi-generation
    reg-basic-sub
    :cow-counter)
;; namespace 'd'
(multi-generation
    reg-basic-sub
    :cow-counter)
```

Will have the :cow-counter overwritten (depending on order in which your namespaces are loaded).

Let me know if that answers your question!

**Comment by fdabrao** [comment]
Hello kiolap, that will solve my needs.
Thanks a lot.
